name: Component Documentation
description: Add Documentation for a component
title: "[Component]: "
labels: ["documentation"]
assignees:
  - kjgarza
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation issue
  - type: textarea
    id: description
    attributes:
      label: Documentation description
      description: Add a short description of the documentation addition or update. Remember to say why, not just what.
      placeholder: 
    validations:
      required: false
 