name: Deploy
on:
  push:
    branches:
      - "master"
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RACK_ENV: stage
      ENV_FILE: .env.stage
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.STAGE_S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build
        run: |
            npm install -y
            hugo --minify

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./public
          bucket: ${{ secrets.STAGE_S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true


